version: '3.8'
services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  redis:
    image: redis:latest

  airflow-webserver:
    image: apache/airflow:2.7.2
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW_HOME: /opt/airflow
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"

  airflow-scheduler:
    image: apache/airflow:2.7.2
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_HOME: /opt/airflow
    volumes:
      - ./airflow:/opt/airflow

  airflow-worker:
    image: apache/airflow:2.7.2
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_HOME: /opt/airflow
    volumes:
      - ./airflow:/opt/airflow

volumes:
  postgres_data: